#!/bin/bash
set -e

echo "🧹 Running SwiftLint on staged files..."

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.swift$" || true)

if [ -z "$FILES" ]; then
  echo "ℹ️ No Swift files staged"
  exit 0
fi
echo ""
echo "----------------------"
echo "👉 Files:"
echo "$FILES"

echo ""
echo "----------------------"
echo "🛠 Formatting..."
swiftformat $FILES

echo ""
echo "----------------------"
echo "📌 Re-staging formatted files..."
git add $FILES

echo ""
echo "----------------------"
echo "🔍 Linting..."
swiftlint lint --strict $FILES

echo ""
echo "----------------------"
echo "✅ SwiftLint passed"
