default_platform(:ios)

platform :ios do

  desc "Run CI tests"
  lane :tests_ci do
    generate
    tests
  end

  desc "Generate project using Tuist"
  lane :generate do
    project_root = File.expand_path("..", Dir.pwd)

    Dir.chdir(project_root) do
      sh("tuist generate")
    end
  end

  desc "Run unit tests"
  lane :tests do
    project_root = File.expand_path("..", Dir.pwd)
    
    Dir.chdir(project_root) do
      sh("rm -rf result.xcresult")
      
      sh("tuist test --result-bundle-path result.xcresult")
      
      sh("which xcresultparser || echo 'NOT FOUND'")
      sh("xcresultparser --version || echo 'NO VERSION'")

      sh("xcresultparser result.xcresult --output junit.xml || echo 'FAILED CONVERSION'")

      sh("ls -la")
    end
  end

end
