default_platform(:ios)

platform :ios do

  desc "Run CI tests"
  lane :tests_ci do
    generate
    tests
  end
  
  desc "Generate project using Tusit"
  lane :generate do
    sh("tuist generate")
  end
  
  desc "Run unit tests"
  lane :tests do
    sh("tuist test")
  end
  
end
