pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                dir('SelfOSLab') {
                    sh '''
                        export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"

                        which ruby
                        ruby -v

                        gem install bundler
                        bundle install
                    '''
                }
            }
        }

        stage('Tests') {
            steps {
                dir('SelfOSLab') {
                    sh '''
                        export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"

                        which ruby
                        ruby -v

                        bundle exec fastlane tests_ci
                    '''
                }
            }
        }
    }
}
