pipeline {
    agent any
    
    environment {
        LANG = "en_US.UTF-8"
        LC_ALL = "en_US.UTF-8"
    }

    stages {
	stage('Setup environment') {
    		steps {
     		   sh '''
       		     set -e
		
      		      echo "🔧 Setting up environment"

       		     # Homebrew (Jenkins-safe)
        		    export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

         		  # ensure brew exists
          		  which brew || (echo "Homebrew not found" && exit 1)

          		  # install rbenv via brew if missing
         		   brew list rbenv >/dev/null 2>&1 || brew install rbenv ruby-build

           		 # initialize rbenv (IMPORTANT)
           		 eval "$(rbenv init - bash)"

          		  # set ruby
         		   rbenv install -s 3.2.2
         		   rbenv global 3.2.2

         		   ruby -v
       		 '''
    		}
	}
	
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                dir('SelfOSLab') {
                    sh '''
                        export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:/opt/homebrew/bin:$PATH"
                        
                        gem install bundler
                        bundle install
                    '''
                }
            }
        }
        
        stage('Generate project') {
            steps {
                dir('SelfOSLab') {
                    sh '''
                        bundle exec fastlane generate
                    '''
                }
            }
        }

        stage('Tests') {
            steps {
                dir('SelfOSLab') {
                    sh '''
                        export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:/opt/homebrew/bin:$PATH"
                        
                        bundle exec fastlane tests
                    '''
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'SelfOSLab/testResult.xcresult/**', fingerprint: true
        }
    }
}
