pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install dependencies') {
            steps {
                dir('SelfOSLab') {
                    sh 'bundle install'
                }
            }
        }
        
        stage('Tests') {
            steps {
                dir('SelfOSLab') {
                    sh 'bundle exec fastlane tests_ci'
                }
            }
        }
    }
}
